#!/bin/bash
# detect-project.sh — shared auto-detection for PROJECT_NAME and SKILL_NAME
# Source this from release.sh and release-audit.sh to eliminate code duplication.
# Requires: PROJECT_ROOT to be set (or defaults to cwd).
# Exports: PROJECT_NAME, SKILL_NAME (only if not already set).
# Exit: 0 success, 1 no skills found (fatal).

_detect_project_name() {
    if [ -z "${PROJECT_NAME:-}" ]; then
        PROJECT_NAME="$(basename "${PROJECT_ROOT:-$(pwd)}" | tr '[:upper:]' '[:lower:]')"
    fi
}

_print_legacy_skill_hints() {
    local root="$1"
    local candidates=()
    local f rel

    while IFS= read -r f; do
        case "$f" in
            */releases/*|*/Release/*|*/backups/*|*/.git/*) continue ;;
        esac
        candidates+=("$f")
    done < <(find "$root" -maxdepth 4 -name SKILL.md -type f 2>/dev/null | sort)

    if [ "${#candidates[@]}" -gt 0 ]; then
        _write_gitx_upgrade_guideline "$root" "${candidates[@]}"
        echo "   发现可能的旧式 flat skill bundle（非 GitX 标准布局）:" >&2
        for f in "${candidates[@]}"; do
            rel="${f#$root/}"
            echo "     - $rel" >&2
        done
        echo "   已生成升级指南: $root/GitX_Upgrade_Guideline.md" >&2
        echo "   GitX 需要标准布局:" >&2
        echo "     $root/skills/<skill-name>/SKILL.md" >&2
        echo "     $root/skills/<skill-name>/VERSION" >&2
        echo "     $root/tests/run_all.sh" >&2
        echo "     $root/scripts/ 与 $root/skills/<skill-name>/scripts/ 双源一致" >&2
        echo "   注意：只设置 SKILL_NAME 不会创建上述路径；请先迁移旧项目或补齐兼容层。" >&2
    fi
}

_skill_name_from_file() {
    local file="$1"
    awk '
        /^---[[:space:]]*$/ { fence++; next }
        fence == 1 && /^name:[[:space:]]*/ {
            sub(/^name:[[:space:]]*/, "", $0)
            gsub(/^["'\'']|["'\'']$/, "", $0)
            print $0
            exit
        }
    ' "$file"
}

_write_gitx_upgrade_guideline() {
    local root="$1"
    shift
    local guide="$root/GitX_Upgrade_Guideline.md"
    local primary="$1"
    local detected_skill rel primary_rel skill_name date
    date="$(date +%Y-%m-%d)"
    primary_rel="${primary#$root/}"
    detected_skill="$(_skill_name_from_file "$primary" 2>/dev/null || true)"
    skill_name="${detected_skill:-<skill-name>}"

    {
        echo "# GitX Upgrade Guideline"
        echo ""
        echo "> Generated by GitX because this project is not in the standard release layout. GitX stopped before release and did not migrate files automatically."
        echo ""
        echo "- Generated: $date"
        echo "- Project root: \`$root\`"
        echo "- Primary legacy candidate: \`$primary_rel\`"
        echo "- Detected skill name: \`$skill_name\`"
        echo ""
        echo "## 1. Current Diagnosis"
        echo ""
        echo "GitX could not find \`skills/*/SKILL.md\`, so the project cannot pass the release pipeline. The current project appears to use a legacy flat skill bundle."
        echo ""
        echo "Detected candidates:"
        for f in "$@"; do
            rel="${f#$root/}"
            echo "- \`$rel\`"
        done
        echo ""
        echo "## 2. Target GitX Layout"
        echo ""
        echo "\`\`\`text"
        echo "skills/$skill_name/SKILL.md"
        echo "skills/$skill_name/VERSION"
        echo "skills/$skill_name/commands/"
        echo "skills/$skill_name/references/"
        echo "skills/$skill_name/assets/"
        echo "skills/$skill_name/scripts/"
        echo "scripts/"
        echo "tests/run_all.sh"
        echo "Release/"
        echo "\`\`\`"
        echo ""
        echo "## 3. Non-Negotiable Safety Rules"
        echo ""
        echo "- No behavior change before RED."
        echo "- No fake RED: syntax errors, import/path errors, or \`assert true\` do not count."
        echo "- No test harness, no silent bypass: create the smallest useful \`tests/run_all.sh\` first."
        echo "- No completion claim without evidence: every step needs command output or direct file inspection."
        echo "- No broad blind rewrite: migrate structure with surgical patches only."
        echo "- No deletion of unknown intent: do not delete \`releases/\`, \`backups/\`, history, compatibility paths, or unusual defensive logic."
        echo "- No repeated failure with the same hypothesis: after 3 distinct failed hypotheses, stop and report evidence."
        echo "- No hardcoded local paths in project code or release artifacts."
        echo "- 不自动 tag / push，不创建 GitHub Release，不执行任何 upstream 操作。"
        echo ""
        echo "## 4. TDD Migration Plan"
        echo ""
        echo "Run each step as a separate RED -> GREEN -> VERIFY loop. For high-risk changes, repeat the affected test at least 3 consecutive clean rounds."
        echo ""
        echo "### Step 1 — Create the standard skill directory"
        echo "- RED: add or run a structure test that fails because \`skills/$skill_name/SKILL.md\` is missing."
        echo "- GREEN: copy the legacy flat bundle into \`skills/$skill_name/\` without deleting the original."
        echo "- VERIFY: inspect \`skills/$skill_name/SKILL.md\`, \`commands/\`, \`references/\`, and \`assets/\`."
        echo ""
        echo "### Step 2 — Move version out of SKILL.md metadata"
        echo "- RED: add or run a metadata compatibility test that fails on \`metadata:\` in \`SKILL.md\`."
        echo "- GREEN: create \`skills/$skill_name/VERSION\` and root \`VERSION\`; remove Codex-incompatible \`metadata:\` from frontmatter."
        echo "- VERIFY: version files match and \`SKILL.md\` frontmatter only uses loader-compatible keys."
        echo ""
        echo "### Step 3 — Add the minimal test harness"
        echo "- RED: \`bash tests/run_all.sh\` fails because the harness or required checks are missing."
        echo "- GREEN: create the smallest meaningful \`tests/run_all.sh\` that checks structure, metadata, commands, and installer behavior."
        echo "- VERIFY: run \`bash tests/run_all.sh\` three clean rounds."
        echo ""
        echo "### Step 4 — Add GitX script dual-source layout"
        echo "- RED: GitX dual-source check fails because \`scripts/\` or \`skills/$skill_name/scripts/\` is missing."
        echo "- GREEN: add required scripts and keep root \`scripts/\` byte-identical with bundled \`skills/$skill_name/scripts/\`."
        echo "- VERIFY: \`diff -rq scripts/ skills/$skill_name/scripts/\` is clean."
        echo ""
        echo "### Step 5 — Sanitize and release dry-run"
        echo "- RED: run \`bash scripts/release-sanitize.sh .\` and record any findings."
        echo "- GREEN: remove real secrets/local paths or add narrow, documented \`.sanitize-ignore\` entries for safe fixtures."
        echo "- VERIFY: sanity scan clean, then run GitX dry-run."
        echo ""
        echo "## 5. Final Gates"
        echo ""
        echo "\`\`\`bash"
        echo "bash tests/run_all.sh"
        echo "shellcheck -S warning scripts/*.sh skills/$skill_name/scripts/*.sh tests/*.sh"
        echo "bash scripts/release-sanitize.sh ."
        echo "PROJECT_ROOT=\$(pwd) bash ~/.agents/skills/gitx-release/scripts/gitx-release.sh --dry-run"
        echo "PROJECT_ROOT=\$(pwd) bash ~/.agents/skills/gitx-release/scripts/gitx-release.sh"
        echo "\`\`\`"
        echo ""
        echo "Do not run the final release command until every earlier gate is green."
        echo ""
        echo "## 6. Prompt for AI Agent"
        echo ""
        echo "\`\`\`text"
        echo "Read GitX_Upgrade_Guideline.md and migrate this project to the GitX standard layout."
        echo "Use strict TDD: write a failing test first, implement the minimum change, then verify."
        echo "Do not delete legacy releases, backups, or user files. Do not tag or push."
        echo "Keep each task small, record evidence after every step, and stop after 3 distinct failed hypotheses."
        echo "The migration is complete only when tests/run_all.sh, shellcheck, release-sanitize, GitX dry-run, and final GitX release all pass."
        echo "\`\`\`"
    } > "$guide"
}

_detect_skill_name() {
    if [ -n "${SKILL_NAME:-}" ]; then
        return 0
    fi
    local skill_dirs=()
    local root="${PROJECT_ROOT:-$(pwd)}"
    if [ -d "$root/skills" ]; then
        for d in "$root"/skills/*/; do
            local n
            n="$(basename "$d")"
            # P2-1: Configurable exclude patterns via env SKILL_EXCLUDE_PATTERNS
            local exclude="${SKILL_EXCLUDE_PATTERNS:-*-workspace|*-evals}"
            local old_ifs="$IFS" pat
            IFS='|'
            for pat in $exclude; do
                # shellcheck disable=SC2254
                case "$n" in $pat) IFS="$old_ifs"; continue 2 ;; esac
            done
            IFS="$old_ifs"
            [ -f "$d/SKILL.md" ] && skill_dirs+=("$n")
        done
    fi
    if [ "${#skill_dirs[@]}" = "1" ]; then
        SKILL_NAME="${skill_dirs[0]}"
    elif [ "${#skill_dirs[@]}" = "0" ]; then
        echo "❌ 未在 $root/skills/*/ 找到 SKILL.md，无法自动识别 skill" >&2
        _print_legacy_skill_hints "$root"
        echo "   请确认项目结构；若已是标准布局但有多个 skill，请设置 SKILL_NAME=xxx" >&2
        return 1
    else
        echo "❌ 找到多个 skill: ${skill_dirs[*]}" >&2
        echo "   请显式设 SKILL_NAME=xxx" >&2
        return 1
    fi
}

# v1.0.8 hardening (Sec Minor #2): defensively whitelist the charset for
# both names. They flow into rsync --exclude patterns, file paths, and
# many quoted contexts. Today every consumer quotes them so injection is
# bounded, but a `<>"&;|$` in either name would surprise downstream tools
# (and may indicate filesystem corruption / malicious mount).
_validate_name() {
    local var="$1" val="$2"
    case "$val" in
        *[!a-zA-Z0-9._-]*)
            echo "❌ $var contains invalid characters: '$val'" >&2
            echo "   Allowed: a-z A-Z 0-9 . _ -" >&2
            return 1
            ;;
    esac
}

PROJECT_ROOT="${PROJECT_ROOT:-$(pwd)}"
_detect_project_name
# Validate PROJECT_NAME immediately so an obviously-bad name aborts before
# we try to enumerate skills/.
if [ -n "${PROJECT_NAME:-}" ]; then
    _validate_name PROJECT_NAME "$PROJECT_NAME" || return 1
fi
# Detection failure (no skills/, multiple skills, etc.) propagates up via
# _detect_skill_name's return code — preserved as the final exit code of
# this sourced script.
_detect_skill_name || return $?
if [ -n "${SKILL_NAME:-}" ]; then
    _validate_name SKILL_NAME "$SKILL_NAME" || return 1
fi
